[variables]
PHP_CLI_SERVER_WORKERS = "8"

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql", "php83Extensions.gd", "nodejs_22"]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan storage:link --force && php artisan migrate --force && php artisan optimize && PHP_CLI_SERVER_WORKERS=8 php artisan serve --host=0.0.0.0 --port=$PORT"