<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Checkout - Market UMKM Perumahan</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-warm-50 pb-20 text-forest-950 sm:pb-0">
    <x-app-header :unread-notifications="$unreadNotifications ?? 0" :unread-chats="$unreadChats ?? 0" />
    <main class="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-10">
        <div><p class="text-sm font-bold uppercase tracking-[0.2em] text-forest-700">Konfirmasi pesanan</p><h1 class="mt-2 text-3xl font-black sm:text-4xl">Checkout</h1></div>
        @if ($errors->any())<div class="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <div class="mt-8 grid gap-6 lg:grid-cols-[1fr_340px] lg:gap-8">
            <form action="{{ route('checkout.store') }}" method="POST" class="space-y-6">@csrf
                <section class="rounded-2xl bg-warm-white p-4 shadow-soft sm:p-6"><p class="text-sm font-bold uppercase tracking-wider text-forest-700">Informasi pembeli</p><h2 class="mt-2 text-lg font-black sm:text-xl">{{ $buyer->name }}</h2><p class="mt-1 text-sm text-sage-600">{{ $buyer->phone }} &middot; {{ $buyer->address }}, Blok {{ $buyer->block }} No. {{ $buyer->house_number }}</p></section>
                <section class="rounded-2xl bg-warm-white p-4 shadow-soft sm:p-6"><p class="text-sm font-bold uppercase tracking-wider text-forest-700">Alamat pengiriman</p><label class="mt-4 block text-sm font-semibold">Alamat lengkap<input name="shipping_address" value="{{ old('shipping_address', $buyer->address.', Blok '.$buyer->block.' No. '.$buyer->house_number) }}" class="mt-2 w-full rounded-lg border-warm-200" /></label><label class="mt-4 block text-sm font-semibold">Catatan untuk penjual (opsional)<textarea name="shipping_note" rows="2" class="mt-2 w-full rounded-lg border-warm-200">{{ old('shipping_note') }}</textarea></label><p class="mt-2 text-xs text-sage-400">Alamat ini dipakai untuk pesanan yang diantar. Pesanan ambil di toko memakai lokasi toko.</p></section>
                <section class="rounded-2xl bg-warm-white p-4 shadow-soft sm:p-6"><p class="text-sm font-bold uppercase tracking-wider text-forest-700">Pengiriman per toko</p><div class="mt-4 space-y-5">@foreach ($sellerGroups as $group) @php($store = $group['store'])<div class="rounded-xl border border-warm-200 p-4"><div class="flex flex-wrap items-baseline justify-between gap-2"><p class="font-bold">{{ $store->store_name }}</p><p class="text-sm text-sage-500">Subtotal Rp{{ number_format($group['subtotal'], 0, ',', '.') }}</p></div>@if (empty($group['methods']))<p class="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Toko ini belum membuka metode pengiriman.</p>@else<div class="mt-3 grid gap-3 sm:grid-cols-2">@foreach ($group['methods'] as $method)<label class="flex cursor-pointer gap-3 rounded-xl border border-warm-200 p-4"><input type="radio" name="shipping_methods[{{ $store->id }}]" value="{{ $method['value'] }}" required @checked($loop->first)><span><strong class="block">{{ $method['label'] }}</strong><small class="text-sage-500">{{ $method['fee'] > 0 ? 'Ongkir Rp'.number_format($method['fee'], 0, ',', '.') : 'Gratis ongkir' }}</small></span></label>@endforeach</div>@endif @if ($store->min_order_amount > 0)<p class="mt-3 text-xs text-sage-500">Minimal pembelian untuk diantar: Rp{{ number_format($store->min_order_amount, 0, ',', '.') }}@if ($store->free_shipping_threshold) &middot; gratis ongkir mulai Rp{{ number_format($store->free_shipping_threshold, 0, ',', '.') }}@endif</p>@endif</div>@endforeach</div></section>
                <section class="rounded-2xl bg-warm-white p-4 shadow-soft sm:p-6"><p class="text-sm font-bold uppercase tracking-wider text-forest-700">Pembayaran</p><div class="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3 sm:gap-3"><label class="flex cursor-pointer items-start gap-3 rounded-xl border border-warm-200 p-3 sm:p-4"><input type="radio" name="payment_method" value="bank_transfer" required @checked(old('payment_method', 'bank_transfer') === 'bank_transfer')><span class="text-xs font-bold sm:text-sm">Transfer bank</span><small class="mt-1 block text-xs text-sage-500">Transfer ke rekening toko, lalu unggah bukti.</small></label><label class="flex cursor-pointer items-start gap-3 rounded-xl border border-warm-200 p-3 sm:p-4"><input type="radio" name="payment_method" value="qris" required @checked(old('payment_method') === 'qris') @disabled(! $qrisAvailable)><span class="text-xs font-bold sm:text-sm">QRIS</span><small class="mt-1 block text-xs text-sage-500">Pindai QRIS toko, lalu unggah bukti.</small></label><label class="flex cursor-pointer items-start gap-3 rounded-xl border border-warm-200 p-3 sm:p-4"><input type="radio" name="payment_method" value="cod" required @checked(old('payment_method') === 'cod')><span class="text-xs font-bold sm:text-sm">COD</span><small class="mt-1 block text-xs text-sage-500">Bayar saat barang diterima di toko atau diantar.</small></label></div>@unless ($qrisAvailable)<p class="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">QRIS belum tersedia karena ada toko yang belum mengunggah QRIS-nya.</p>@endunless<div id="bank-transfer-details" class="mt-5 space-y-3 rounded-xl bg-forest-50 p-4"><p class="text-sm font-bold text-forest-900">Rekening transfer per toko</p>@foreach ($sellerGroups as $group) @php($store = $group['store'])<div class="border-t border-forest-200 pt-3 text-sm"><p class="font-bold text-forest-900">{{ $store->store_name }}</p>@if ($store->paymentSetting?->bank_name && $store->paymentSetting?->bank_account_number)<p class="mt-1 text-forest-800">{{ $store->paymentSetting->bank_name }} &middot; {{ $store->paymentSetting->bank_account_number }}</p><p class="text-forest-700">a.n. {{ $store->paymentSetting->bank_account_name }}</p>@else<p class="mt-1 text-red-700">Rekening seller belum tersedia.</p>@endif</div>@endforeach</div></section>
                <button class="w-full rounded-xl bg-forest-700 px-5 py-4 font-bold text-white hover:bg-forest-800">Buat pesanan</button>
            </form>
            <aside class="h-fit rounded-2xl bg-forest-950 p-6 text-white lg:sticky lg:top-24"><p class="text-sm text-forest-200">Pesanan Anda</p><div class="mt-5 space-y-4">@foreach ($products as $product)<div class="flex justify-between gap-4 text-sm"><span class="min-w-0">{{ $product->name }} x {{ $quantities[$product->id] }}@if ($product->hasDiscount())<small class="block text-forest-300">diskon {{ $product->discount_percent }}%</small>@endif</span><strong class="shrink-0">Rp{{ number_format($product->effectivePrice() * $quantities[$product->id], 0, ',', '.') }}</strong></div>@endforeach</div><div class="mt-6 space-y-2 border-t border-white/20 pt-5 text-sm"><div class="flex justify-between"><span>Subtotal</span><span>Rp{{ number_format($subtotal, 0, ',', '.') }}</span></div><div class="flex justify-between"><span>Ongkos kirim</span><span>Rp{{ number_format($shippingFee, 0, ',', '.') }}</span></div></div><div class="mt-4 flex justify-between border-t border-white/20 pt-5 text-lg"><span>Total</span><strong>Rp{{ number_format($subtotal + $shippingFee, 0, ',', '.') }}</strong></div></aside>
        </div>
    </main>

    <x-mobile-bottom-nav :unread-notifications="$unreadNotifications ?? 0" :unread-chats="$unreadChats ?? 0" />
    <script>
        const paymentMethods = document.querySelectorAll('input[name="payment_method"]');
        const bankDetails = document.getElementById('bank-transfer-details');
        paymentMethods.forEach((method) => method.addEventListener('change', () => {
            bankDetails.hidden = document.querySelector('input[name="payment_method"]:checked').value !== 'bank_transfer';
        }));
    </script>
</body>
</html>



